/*-------------------------------------------------------------------------
 *
 * model_info_d.h
 *    Macro definitions for model_info
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef MODEL_INFO_D_H
#define MODEL_INFO_D_H

#define ModelInfoRelationId 2023

#define Anum_model_info_modelname 1
#define Anum_model_info_createtime 2
#define Anum_model_info_uploadby 3
#define Anum_model_info_md5 4
#define Anum_model_info_modelpath 5
#define Anum_model_info_description 6
#define Anum_model_info_updatetime 7

#define Natts_model_info 7


#endif							/* MODEL_INFO_D_H */
